code --install-extension budparr.language-hugo-vscode
code --install-extension chrischinchilla.vale-vscode
code --install-extension connor4312.esbuild-problem-matchers
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension GitLab.gitlab-workflow
code --install-extension golang.go
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension redhat.java
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension znck.grammarly
